apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iris-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: <host_name>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: iriswebapp-app
            port:
              number: 80 